[project]
name = "scraper-etykiety-srodkow-ochrony-roslin"
version = "0.1.0"
description = "Etykiety, zezwolenia, pozwolenia i decyzje środków ochrony roślin zarejestrowanych w Polsce https://www.gov.pl/web/rolnictwo/etykiety-srodkow-ochrony-roslin"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
